postgresql:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  ports:
    - 15432:5432
  volumes:
    - postgresql.volume:/var/lib/postgresql/data
  container_name: postgres-db